apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: devops
spec:
  selector:
    role: backend
  ports:
    - protocol: TCP
      port: 3500       # Internal Cluster Port
      targetPort: 3500 # Container Port
  type: ClusterIP
